#!/bin/bash
DEST=../druid/server/src/main/resources/static
export PATH="$ROOT_DIR/node/current/bin:$ROOT_DIR/node_modules/.bin:$PATH"

if [ ! -d build ]; then
  mkdir -p build
fi

compass compile --sass-dir src/client --css-dir build

browserify -t coffeeify --extension=".coffee" src/client/druid.coffee -o build/druid.js

cp -R static/css static/fonts static/pages static/favicon.ico build/* $DEST
cp -R static/console.html $DEST/index.html
